import { notFound } from "next/navigation";
import Link from "next/link";
import { getSupabaseAdmin } from "@/lib/supabaseAdmin";
import { saveBriefingPreferences } from "./actions";
import OwnerBottomNav,{OwnerTopNav} from "@/components/owner/OwnerBottomNav";
export const dynamic="force-dynamic";
const checks=[['include_reservations','Réservations nouvelles, modifiées ou annulées'],['include_cleaning_completed','Missions terminées et photos'],['include_cleaner_accepted','Mission acceptée'],['include_cleaner_refused','Mission refusée'],['include_cleaning_rescheduled','Mission replanifiée'],['include_pricing','Variations de prix'],['include_min_stay','Séjours minimums modifiés']] as const;
export default async function Page({params}:{params:Promise<{ownerToken:string}>}){const {ownerToken}=await params;const db=getSupabaseAdmin();const {data:owner}=await db.from('owners').select('id,name,display_name').eq('public_token',decodeURIComponent(ownerToken)).eq('active',true).maybeSingle();if(!owner)notFound();const [pr,dr,br,pf]=await Promise.all([db.from('properties').select('id,name,status').eq('owner_id',owner.id).order('name'),db.from('ops_decisions').select('*').eq('owner_id',owner.id).order('occurred_at',{ascending:false}).limit(100),db.from('ops_briefings').select('*').eq('owner_id',owner.id).order('generated_at',{ascending:false}).limit(12),db.from('ops_briefing_preferences').select('*').eq('owner_id',owner.id).maybeSingle()]);const properties=pr.data??[],decisions=dr.data??[],briefings=br.data??[],pref=pf.data??{};const selected=new Set(pref.included_property_ids??properties.map((p:any)=>p.id));return <main className="min-h-screen bg-[#f2eee6] text-[#112532]"><div className="mx-auto max-w-6xl px-4 py-5 pb-24"><OwnerTopNav active="activity"/><div className="mt-8 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#e0680e]">Pilotys Activity</p><h1 className="text-3xl font-black">Ce qui s’est passé, pourquoi, et ce que Pilotys a fait</h1></div><Link className="rounded-full bg-white px-4 py-2 text-sm font-bold shadow" href={`/owner/${encodeURIComponent(ownerToken)}/cockpit`}>Retour au cockpit</Link></div>
<section className="mt-6 grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><div className="space-y-3">{decisions.length?decisions.map((d:any)=><details key={d.id} className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-black/5"><summary className="cursor-pointer list-none"><div className="flex gap-3"><span className={`mt-1 h-3 w-3 rounded-full ${d.requires_owner_action?'bg-red-500':d.category==='pricing'?'bg-amber-500':d.category==='cleaning'?'bg-emerald-500':'bg-sky-500'}`}/><div><div className="font-black">{d.title}</div><div className="text-sm text-[#112532]/60">{d.summary} · {new Date(d.occurred_at).toLocaleString('fr-FR')}</div></div></div></summary><div className="mt-4 grid gap-3 md:grid-cols-3"><Info title="Ce qui s’est passé" text={d.what_happened}/><Info title="Pourquoi" text={d.why}/><Info title="Ce que Pilotys a fait" text={d.action_taken}/></div></details>):<div className="rounded-3xl bg-white p-8">Aucune activité enregistrée pour le moment.</div>}</div>
<div className="space-y-5"><form action={saveBriefingPreferences} className="rounded-3xl bg-white p-5 shadow-sm"><input type="hidden" name="owner_token" value={ownerToken}/><h2 className="text-xl font-black">Briefing SMS</h2><label className="mt-4 flex gap-2 font-bold"><input type="checkbox" name="enabled" defaultChecked={!!pref.enabled}/> Activer les briefings</label><div className="mt-4 grid grid-cols-2 gap-3"><Field label="Téléphone 1" name="recipient_1_phone" value={pref.recipient_1_phone}/><Field label="Téléphone 2" name="recipient_2_phone" value={pref.recipient_2_phone}/><label className="text-sm font-bold">Fréquence<select name="frequency" defaultValue={pref.frequency??'morning'} className="mt-1 w-full rounded-xl border p-2"><option value="immediate">Dès que possible</option><option value="morning">Chaque matin</option><option value="evening">Chaque soir</option><option value="daily">Une fois par jour</option><option value="weekly">Chaque semaine</option></select></label><Field label="Heure" name="delivery_hour" type="number" value={pref.delivery_hour??8}/></div><h3 className="mt-5 font-black">Logements inclus</h3>{properties.map((p:any)=><label key={p.id} className="mt-2 flex gap-2 text-sm"><input type="checkbox" name="property_ids" value={p.id} defaultChecked={selected.has(p.id)}/>{p.name}</label>)}<h3 className="mt-5 font-black">À inclure</h3>{checks.map(([name,label])=><label key={name} className="mt-2 flex gap-2 text-sm"><input type="checkbox" name={name} defaultChecked={pref[name]??true}/>{label}</label>)}<div className="mt-4 grid grid-cols-2 gap-3"><label className="text-sm font-bold">Seuil prix<select name="pricing_threshold_type" defaultValue={pref.pricing_threshold_type??'pct'} className="mt-1 w-full rounded-xl border p-2"><option value="pct">Pourcentage</option><option value="eur">Euros</option></select></label><Field label="Valeur" name="pricing_threshold_value" type="number" value={pref.pricing_threshold_value??2}/></div><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" name="include_temporal_daily" defaultChecked={pref.include_temporal_daily??true}/> Mentionner chaque jour les ajustements temporels regroupés</label><button className="mt-5 w-full rounded-2xl bg-[#112532] px-4 py-3 font-black text-white">Enregistrer</button></form>{briefings.length>0&&<div className="rounded-3xl bg-white p-5"><h2 className="font-black">Derniers briefings</h2>{briefings.map((b:any)=><details key={b.id} className="mt-3 border-t pt-3"><summary className="cursor-pointer text-sm font-bold">{new Date(b.generated_at).toLocaleString('fr-FR')} · {b.decision_count} élément(s)</summary><pre className="mt-2 whitespace-pre-wrap text-sm">{b.body}</pre></details>)}</div>}</div></section></div><OwnerBottomNav active="activity"/></main>}
function Info({title,text}:{title:string,text?:string}){return <div className="rounded-2xl bg-[#f7f4ee] p-3"><div className="text-xs font-black uppercase text-[#112532]/45">{title}</div><div className="mt-1 text-sm">{text||'—'}</div></div>}
function Field({label,name,value,type='text'}:{label:string,name:string,value?:any,type?:string}){return <label className="text-sm font-bold">{label}<input name={name} type={type} defaultValue={value??''} className="mt-1 w-full rounded-xl border p-2"/></label>}
