"use client";
import { useMemo, useState } from "react";
type Row=Record<string,any>;
const eur=(v:any)=>v==null?"—":new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(Number(v));
const label:Record<string,string>={base_plan:"Plan général",season_plan:"Saison",market_signal:"Signal marché",time_optimisation:"Courbe temporelle",guardrail:"Limites",premium_single_night:"Nuit isolée",manual_override:"Manuel"};
export default function ExplainablePricingCalendar({rows}:{rows:Row[]}){
 const [selected,setSelected]=useState<Row|null>(null); const [offset,setOffset]=useState(0);
 const months=useMemo(()=>{const m=new Map<string,Row[]>();for(const r of rows){const k=String(r.date).slice(0,7);m.set(k,[...(m.get(k)||[]),r]);}return [...m.entries()];},[rows]);
 const current=months[Math.max(0,Math.min(offset,months.length-1))]; if(!current)return <p>Aucun calendrier calculé.</p>;
 const [key,days]=current;const first=new Date(`${key}-01T12:00:00`);const blanks=(first.getDay()+6)%7;
 return <><div className="calHead"><button type="button" onClick={()=>setOffset(Math.max(0,offset-1))}>←</button><h2>{first.toLocaleDateString("fr-FR",{month:"long",year:"numeric"})}</h2><button type="button" onClick={()=>setOffset(Math.min(months.length-1,offset+1))}>→</button></div>
 <div className="week">{["Lun","Mar","Mer","Jeu","Ven","Sam","Dim"].map(x=><b key={x}>{x}</b>)}</div><div className="grid">{Array.from({length:blanks}).map((_,i)=><div key={`b${i}`} />)}{days.map(r=><button type="button" key={r.date} className={`day ${r.occupied?"occupied":""}`} onClick={()=>setSelected(r)}><span>{Number(String(r.date).slice(8))}</span><strong>{eur(r.final_price)}</strong><small>{(r.explanation_steps||[]).slice(-2).map((s:Row)=>label[s.kind]||s.label).join(" · ")}</small></button>)}</div>
 {selected&&<div className="drawer"><button className="close" onClick={()=>setSelected(null)}>×</button><h2>{new Date(`${selected.date}T12:00:00`).toLocaleDateString("fr-FR",{weekday:"long",day:"numeric",month:"long"})}</h2><div className="final">Prix final <strong>{eur(selected.final_price)}</strong> · {selected.min_stay} nuit(s)</div>{(selected.explanation_steps||[]).map((s:Row,i:number)=><div className="step" key={i}><div><b>{s.label}</b><p>{s.explanation}</p></div><div>{eur(s.before_eur)} → <strong>{eur(s.after_eur)}</strong>{s.delta_eur? <small>{s.delta_eur>0?"+":""}{eur(s.delta_eur)}</small>:null}</div></div>)}</div>}
 <style jsx>{`.calHead{display:flex;align-items:center;justify-content:space-between}.calHead button{width:40px}.week,.grid{display:grid;grid-template-columns:repeat(7,1fr);gap:6px}.week b{text-align:center;font-size:12px;padding:8px}.day{min-height:100px;background:white;color:#0f172a;text-align:left;padding:8px;border:1px solid #e2e8f0}.day strong,.day small{display:block;margin-top:8px}.day small{font-size:10px;color:#64748b}.occupied{opacity:.5;background:#f1f5f9}.drawer{position:fixed;right:0;top:0;height:100vh;width:min(480px,95vw);background:white;z-index:50;padding:28px;box-shadow:-12px 0 30px #0002;overflow:auto}.close{float:right}.final{padding:16px;background:#f8fafc;border-radius:12px;margin:18px 0}.step{display:flex;justify-content:space-between;gap:20px;padding:16px 0;border-bottom:1px solid #e2e8f0}.step p{margin:5px 0;color:#475569;font-size:13px}.step small{display:block;text-align:right;color:#64748b}@media(max-width:700px){.day{min-height:74px;padding:5px}.day small{display:none}.week,.grid{gap:3px}}`}</style></>;
}
