"use client";
import type {CSSProperties,ReactNode} from "react";
import CurvePresetSelector from "./CurvePresetSelector";
import SubmitStatusButton from "./SubmitStatusButton";
type Row=Record<string,any>;
const input={font:"inherit",padding:"9px 10px",border:"1px solid #cbd5e1",borderRadius:9,width:"100%"} as const;const field={display:"grid",gap:5,fontWeight:600} as const;
export default function SeasonEditor({season,hiddenFields,saveAction,deleteAction}:{season?:Row;hiddenFields:ReactNode;saveAction:(f:FormData)=>void;deleteAction:(f:FormData)=>void}){const x=season||{};const isNew=!season;const mode=x.optimisation_mode??(x.protect_from_automatic_reductions?"none":x.optimisation_curve?"custom":"inherit");return <details open={isNew} style={{border:"1px solid #e2e8f0",borderRadius:14,padding:14,background:"white"}}><summary style={{cursor:"pointer",fontWeight:800,fontSize:16}}>{isNew?"Ajouter une saison":`${x.name} · ${x.start_date} → ${x.end_date}`}</summary><form action={saveAction} style={{display:"grid",gap:16,marginTop:16}}>{hiddenFields}{season&&<input type="hidden" name="id" value={x.id}/>}<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(165px,1fr))",gap:10}}>
 <label style={field}>Nom<input name="name" defaultValue={x.name??""} placeholder="Été / Noël…" required style={input}/></label><label style={field}>Début<input name="start_date" type="date" defaultValue={x.start_date??""} required style={input}/></label><label style={field}>Fin<input name="end_date" type="date" defaultValue={x.end_date??""} required style={input}/></label>
 <label style={field}>Semaine<input name="weekday_price" type="number" step=".01" defaultValue={x.weekday_price??""} required style={input}/></label><label style={field}>Vendredi / samedi<input name="weekend_price" type="number" step=".01" defaultValue={x.weekend_price??""} style={input}/></label><label style={field}>Plancher<input name="floor_price" type="number" step=".01" defaultValue={x.floor_price??""} style={input}/></label><label style={field}>Plafond<input name="ceiling_price" type="number" step=".01" defaultValue={x.ceiling_price??""} style={input}/></label><label style={field}>Séjour minimum<input name="min_stay" type="number" min="1" defaultValue={x.min_stay??2} style={input}/></label><label style={field}>Influence Goyen (%)<input name="market_signal_influence_pct" type="number" min="0" max="100" defaultValue={x.market_signal_influence_pct??""} style={input}/></label>
 </div><div><h4 style={{margin:"0 0 10px"}}>Baisse temporelle de cette saison</h4><CurvePresetSelector namePrefix="season_" allowInherit mode={mode} initialPreset={x.optimisation_preset??"progressive"} initialHorizon={x.optimisation_horizon_days??120} initialMaxDiscount={x.optimisation_max_discount_pct??20}/></div><div style={{display:"flex",justifyContent:"flex-end",gap:9,flexWrap:"wrap"}}>{season&&<button formAction={deleteAction} name="id" value={x.id} style={{...button,background:"white",color:"#b91c1c",border:"1px solid #fecaca"}}>Retirer</button>}<SubmitStatusButton idle={isNew?"Ajouter et recalculer":"Enregistrer et recalculer"} pending="Recalcul en cours…"/></div></form></details>}
const button:CSSProperties={font:"inherit",padding:"10px 14px",borderRadius:10,cursor:"pointer"};
